name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # The branch you want to deploy from

permissions:
  contents: write  # Allow write access to repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Adjust if needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
          publish_dir: ./build  # Adjust based on your output directory
          publish_branch: gh-pages
